//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Department
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public int deliveryNUM { get; set; }
        public System.DateTime deliveryDATE { get; set; }
        public decimal goodsCOUNT { get; set; }
        public int goodsNUM { get; set; }
        public int supplierNUM { get; set; }
        public int workersNUM { get; set; }
        public int storageNUM { get; set; }
    
        public virtual goods goods { get; set; }
        public virtual storage storage { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual workers workers { get; set; }
    }
}
