//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Department
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DepartmentEntities : DbContext
    {
        public DepartmentEntities()
            : base("name=DepartmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<benefits> benefits { get; set; }
        public virtual DbSet<cech> cech { get; set; }
        public virtual DbSet<delivery> delivery { get; set; }
        public virtual DbSet<goods> goods { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<person_benefits> person_benefits { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<storage> storage { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<workers> workers { get; set; }
    }
}
